### ISSUE TITLE
Mask not apply after change text

### ISSUE THREAD

**Issue by ABPSoft** [AliAzaz/Edittext-Picker#2]
Hi
My mask was: ####-####-####-####

But when I change this input text with programmatically, mask not apply on it.

Please fix it.
Thanks

**Comment by AliAzaz** [comment]
Hi,

Are u using androidX or other support library?

**Comment by ABPSoft** [comment]
Yes,
I'm using androidX.

It's my code:
`
 <com.edittextpicker.aliazaz.EditTextPicker
                            android:id="@+id/cardNumber"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:background="@android:color/transparent"
                            android:hint="Card Number"
                            android:inputType="number"
                            android:maxLength="16"
                            android:paddingTop="3dp"
                            android:textAlignment="center"
                            android:textColor="@color/baseColor"
                            android:textColorHint="#fff"
                            android:textDirection="ltr"
                            android:textSize="@dimen/text_size_f"
                            app:mask="####-####-####-####" />
`

my java code:
`cardNumber.setText("6362141086509187");`

**Comment by AliAzaz** [comment]
Sorry for the late reply. It will resolve in the next release.

**Comment by AliAzaz** [comment]
Fixed in Release -v2.1.0
