### ISSUE TITLE
Consider making EditTextPicker open so users can derive and extend

### ISSUE THREAD

**Issue by kenargo** [AliAzaz/Edittext-Picker#3]
In Kotlin classes are, by default 'final'.  Would you consider marking the EditTextPicker as 'open' so the library can be derived and extended rather than branch the whole project?

**Comment by AliAzaz** [comment]
It's open for PR. Kindly do implement and push the request, we will review it.

**Comment by AliAzaz** [comment]
I'm closing this issue. If you want any change then please do create PR, we will review it and let you know it's fine or not.
