### ISSUE TITLE
Changing the mask doesn't work

### ISSUE THREAD

**Issue by fuzzball1980** [AliAzaz/Edittext-Picker#9]
Hi!

If I created the component on XML and then try to change the mask on code it doesn't change. Even if I dont set the mask on the XML and just set it programatically it doesnt work.

<com.edittextpicker.aliazaz.EditTextPicker
                android:id="@+id/field1"
                android:layout_width="match_parent"
                android:layout_height="50dp"
                app:mask="##-(##)-####"
                android:textColor="@android:color/white"
                android:textColorHint="@color/transparent_white"
                android:textCursorDrawable="@null"
                android:textSize="@dimen/login_edit_text_size"
                android:background="@drawable/edit_text_white_underline"
                android:gravity="center"
                />

field1.setMask("##-(##)-####");

any idea?

Thanks!

**Comment by AliAzaz** [comment]
It would be done in the next release. Thanks for your patience.

**Comment by AliAzaz** [comment]
Fixed in Release -v2.1.0
